name: GitHub Webhook Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Webhook
      run: |
        $NGROK_URL = "https://9e0f-81-56-206-25.ngrok-free.app/ckbapp/github_webhook/"

        # Directly use the event payload without conversion
        $WEBHOOK_PAYLOAD = Get-Content $env:GITHUB_EVENT_PATH

        Write-Host "Webhook Payload: $WEBHOOK_PAYLOAD"

        # Send the entire payload to the external platform
        Invoke-RestMethod -Uri $NGROK_URL -Method Post -Body $WEBHOOK_PAYLOAD -ContentType "application/json"
