name: GitHub Webhook Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Trigger Webhook
      run: |
        $NGROK_URL = "https://9e0f-81-56-206-25.ngrok-free.app/ckbapp/github_webhook/"

        # Get the entire webhook payload
        $WEBHOOK_PAYLOAD = (cat $GITHUB_EVENT_PATH | ConvertFrom-Json | ConvertTo-Json)

        Write-Host "Webhook Payload: $WEBHOOK_PAYLOAD"

        # Send the entire payload to the external platform
        curl -X POST -H "Content-Type: application/json" -d "$WEBHOOK_PAYLOAD" $NGROK_URL
