name: Construct Payload with Changed File

on:
  push:
    branches:
      - main

jobs:
  construct-payload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Construct Payload
      run: |
        # Get the changed file(s)
        changed_file=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        # Create a payload with the changed file(s)
        payload="{\"changed_file\":\"$changed_file\"}"

        # Print the payload
        echo "Constructed Payload: $payload"

        # Use the payload as needed, e.g., pass it to an external service or save it for later use
      env:
        CHANGED_FILE: $changed_file
