name: Invia a piattaforma amico

on:
  push:
    paths:
      - 'code_katas/code_kata.py'

jobs:
  send-to-platform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Invia richiesta POST alla piattaforma
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "file_content": "$(cat code_kata.py)",
            "committer_info": "${{ github.actor }}",
            "commit_info": "${{ github.event.head_commit.message }}"
          }' https://9e0f-81-56-206-25.ngrok-free.app/ckbapp/github_webhook/
