name: GitHub Webhook Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger_webhook:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        choco install jq

    - name: Get commit details
      id: commit
      run: |
        $COMMIT_MESSAGE = git log --format="%B" -n 1 $env:GITHUB_SHA
        $COMMIT_AUTHOR = git log --format="%an" -n 1 $env:GITHUB_SHA
        $COMMIT_URL = git log --format="%H" -n 1

        echo "::set-output name=COMMIT_MESSAGE::$COMMIT_MESSAGE"
        echo "::set-output name=COMMIT_AUTHOR::$COMMIT_AUTHOR"
        echo "::set-output name=COMMIT_URL::$COMMIT_URL"

    - name: Fetch pushed code
      id: fetch_code
      run: |
        $COMMIT_SHA = (git log --format='%H' -n 1)
        $FILE_PATH = "codeKata3/b/code_katas/code_kata.py"
        $RAW_CONTENT_URL = "https://raw.githubusercontent.com/${env:GITHUB_REPOSITORY}/${COMMIT_SHA}/${FILE_PATH}"
        $PUSHED_CODE = (curl -sSL $RAW_CONTENT_URL)

        echo "::set-output name=PUSHED_CODE::$PUSHED_CODE"
        echo "PUSHED_CODE=$PUSHED_CODE" >> $GITHUB_ENV

    - name: Debug Payload Variables
      run: |
        Write-Host "Commit SHA: $env:COMMIT_SHA"
        Write-Host "File Path: $env:FILE_PATH"
        Write-Host "Raw Content URL: $env:RAW_CONTENT_URL"
        Write-Host "Pushed Code: $env:PUSHED_CODE"

    - name: Trigger Webhook
      run: |
        $NGROK_URL = "https://9e0f-81-56-206-25.ngrok-free.app/ckbapp/github_webhook/"
        $PAYLOAD = @{
          message = $env:COMMIT_MESSAGE
          author = $env:COMMIT_AUTHOR
          url = $env:COMMIT_URL
          pushed_code = $env:PUSHED_CODE
        } | ConvertTo-Json

        Write-Host "Payload Content: $PAYLOAD"

        curl -X POST -H "Content-Type: application/json" -d $PAYLOAD $NGROK_URL
